### ISSUE TITLE
2.0.0 Release Checklist

### ISSUE THREAD

**Issue by timothyasp** [iFixit/iFixitAndroid#148]
# Play Store
- [x] Update Play store description
- [x] Update screenshots
- [x] Translate play store description into french, spanish and german
- [x] Add video to play store
# App
- [x] Prepare new strings for translation
- [x] Translate new strings
- [ ] ~~Step Edit Help dialog~~
- [x] Tag release and release notes
# Github
- [x] Readme update
- [x] Add CLA
# Misc
- [x] Update device screenshots on the [apps page](http://www.ifixit.com/Apps).
