### ISSUE TITLE
Guide Creation release todo

### ISSUE THREAD

**Issue by timothyasp** [iFixit/iFixitAndroid#43]
Before we can release the new guide creation functionality to the public (well non-source-building public), we need to address these issues.
## Build + documentation
- [ ] Update readme to include new build instructions for maven with eclipse, intellij and command line. Also update endpoints used.
- [ ] Make sure all dependencies are in some central repository, or at least write a script that downloads and installs all the maven dependencies locally so others building the app can easily get started.
- [ ] Add maven-release-plugin and get the app set up to push tags, update the manifest and export + sign the apk.
## Miscellaneous Pages
- [ ] Help Pages
- [ ] About Page
- [ ] Device Search
## User Guide List
- [x] Add refresh to guide list view.  Right now the only way to refresh the guide list is to kill the app and reload it.
- [x] Editing any guide unpublishes the guide.
- [ ] Expanding the last element in the list view in guide list doesn't move the screen with it, so you have to flick down to see the options.  Also should add some extra padding between the bottom element and the page, that might help as well.
## Create New Guide
- [x] There is no back button option on the logo when editing or creating an introduction.  You have to use the hardware back.
- [x] Device input field needs to autocomplete or at least give a dropdown of options of possible devices or the option to create a new device/topic.  Needs to be topic in the dozuki app. 
- [x] Introduction field in the guide intro is outputting `introduction_rendered` which is the HTML output. Should be bringing in `introduction_raw`.  After saving the intro, the characters are run through html_entites which fucks up all the html into a bunch of goblygunk. 
- [x] Focus should be renamed to subject(?) and it's currently not being populated or saved. 
## Step Creation
- [x] Tapping an empty thumbnail to add an image should let you capture and attach the image directly rather than having to go through the media manager which takes 5 steps to capture and attach the image currently.  This is a critical feature before release since the primary use case we've identified for this app is stubbing out a guide with pictures, then adding text later on the computer.
- [x] Step reorder "Done" vs "Confirm" options are not intuative. The first two times I interacted with it, I thought "Done" was the option to save the step reordering (The checkmark makes it confusing) and I thought it was a bug when it didn't work.  "Confirm" is actually what saves.
- [x] Step line text form fields need to be multiline, without newlines.  single line is unuseable when editing existing guide steps or reviewing added text.
- [x] Tapping the main guide image in step create/edit does nothing.  It should bring up a full size image just like the step view. 
- [ ] Clicking confirm on reorder steps without doing anything still sends off a request.  We should check to see if the order changed at all to prevent useless queries. 
- [x] Clean up thumbnail code.  Should use ThumbnailView, instead of explicitly setting each image...
- [ ] Drag and drop reorder thumbnail images
- [x] "+" Icon add images if > 1 and < 3
## General
- [ ] Help text needs to be updated.
- [ ] API Error alert dialogs are just using a generic message right now - we should use the specific API error messages.
- [x] Full screen gray background spinner is ugly (actually the generic spinner in general).  It works on long loads, but for short updates, it's not noticeable that it's a loading spinner and it just looks like the page is flickering
- [x] Logging out needs to clear the guide list and bring up the login dialog
- [x] When paging quickly through steps, loading images show no indication that they are loading.  They just pop in.  should have at least a placeholder for them to show something should be there.  
- [ ] Deleting a guide or step needs more ominous/serious warning text.  Deleting a guide is unrecoverable, so it's serious business when you do.  The app makes it really easy to do that, so we need to make sure the user understands.
- [x] We need buttons to view a guide on the user guide list and on step edit.
- [ ] The ordering of tabs on topic view (guides, answers, info) might need to be changed to (guides, info, answers) to avoid bugs with sites without answers.
- [x] Navigation overhaul
## 10in Tablet
- [x] Layout optimizations.  Tablet view is basically the same as the phone, just 1.5-2.5 times bigger.  We should take advantage of the extra screen space.
- [x] Main image is using .standard or .medium size and is about the same size as the thumbnails.  Thumbnails are also too large so they are blurry.  Should use same sizes as guide view
- [x] Tapping any element in portrait mode (like edit guide) rotates the screen 180degress while saving (full screen spinner) and then rotates back.
